name: mini_project_e2e_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  date_picker_plus: ^7.0.0
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  intl: ^0.20.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/mini_project_e2e.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/mini_project_e2e.png"
